version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - cuda
  - fabs
  - gettime
  - malloc
  - matmul
  - memcpy
  - nsec
  - nvtx
  - srand
  - timespec
ignoreWords: []
import: []
